language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - npm install
script: grunt test --verbose --force
#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#example"
